# Generated by Django 2.1.7 on 2019-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sztu_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
