# Generated by Django 2.1.7 on 2019-03-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sztu_api', '0002_click_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='name',
            new_name='dom_name',
        ),
    ]
