# Generated by Django 2.1.7 on 2019-03-08 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sztu_api', '0003_auto_20190308_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
